name: Release Test

on: workflow_dispatch

jobs:
  release_test:
    name: Try build the release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-18.04'
#          - 'windows-2019'
          - 'macos-10.15'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 20

      - name: Set up QEMU
        if: ${{ runner.os == 'Linux' }}
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.7.0

      - name: Show the buildings
        shell: bash
        run: |
          ls -al ./wheelhouse
      - name: Upload packed files to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-${{ matrix.os }}
          path: ./wheelhouse/*
