name: Code Script Run

on:
  push:
    branches: [ 'run/*' ]

jobs:
  unittest:
    name: Code Script Run
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-20.04'
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 20
      - name: Set up system dependences on linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y tree cloc wget curl make graphviz
          sudo apt-get install -y libxml2-dev libxslt-dev python-dev  # need by pypy3
          dot -V
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          pip install -r requirements.txt
          pip install -r requirements-build.txt
          pip install -r requirements-test.txt
          pip install .
      - name: Test the basic environment
        run: |
          python -V
          pip --version
          pip list
          tree .
          cloc treevalue
          cloc test
      - name: Run Script
        env:
          CI: 'true'
          LINETRACE: 1
        run: |
          make clean build run
      - name: Show the artifacts
        run: |
          tree runs/artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: run-artifacts-${{ matrix.os }}-${{ matrix.python-version }}
          path: runs/artifacts
